// TypeScript Version: 3.0

/// <reference path="./themes.d.ts"/>

import * as React from 'react'

import { IconBaseTheme } from 'grommet-icons/themes'
import { FilterObjectKeys, Omit } from 'types-util'

declare module 'grommet-icons' {
  // Themable type values
  type ColorNames<T extends IconBaseTheme = IconBaseTheme> = FilterObjectKeys<
    T['global']['colors'],
    string
  >

  type ColorValue<T extends IconBaseTheme = IconBaseTheme> =
    | ColorNames<T>
    | {
        dark?: ColorNames<T>
        light?: ColorNames<T>
      }

  type ColorProp<
    T extends IconBaseTheme = IconBaseTheme
  > = keyof T['global']['colors']

  type IconSizeProp<
    T extends IconBaseTheme = IconBaseTheme
  > = keyof T['icon']['size']

  interface IconProps<T extends IconBaseTheme = IconBaseTheme> {
    a11yTitle?: string
    size?: IconSizeProp<T>
    color?: ColorProp<T>
  }

  type OmittedSvgProps = "size"

  type IconI<T extends IconBaseTheme = IconBaseTheme> = React.ComponentType<
    IconProps<T> & Omit<JSX.IntrinsicElements['svg'], OmittedSvgProps>
  >

  const Accessibility: IconI
  const Achievement: IconI
  const Action: IconI
  const Actions: IconI
  const Ad: IconI
  const Add: IconI
  const AddCircle: IconI
  const Aed: IconI
  const Aggregate: IconI
  const Aid: IconI
  const AidOption: IconI
  const Alarm: IconI
  const Alert: IconI
  const Amazon: IconI
  const Amex: IconI
  const Analytics: IconI
  const Anchor: IconI
  const Android: IconI
  const Announce: IconI
  const Apple: IconI
  const Apps: IconI
  const Archive: IconI
  const Archlinux: IconI
  const Article: IconI
  const Aruba: IconI
  const Ascend: IconI
  const AssistListening: IconI
  const Atm: IconI
  const Attachment: IconI
  const Attraction: IconI
  const Baby: IconI
  const BackTen: IconI
  const Bar: IconI
  const BarChart: IconI
  const Basket: IconI
  const Bike: IconI
  const Bitcoin: IconI
  const Blank: IconI
  const BlockQuote: IconI
  const Blog: IconI
  const Bluetooth: IconI
  const Bold: IconI
  const Book: IconI
  const Bookmark: IconI
  const BottomCorner: IconI
  const Braille: IconI
  const Briefcase: IconI
  const Brush: IconI
  const Bug: IconI
  const Bundle: IconI
  const Bus: IconI
  const BusinessService: IconI
  const Cafeteria: IconI
  const Calculator: IconI
  const Calendar: IconI
  const Camera: IconI
  const Capacity: IconI
  const Car: IconI
  const CaretDown: IconI
  const CaretNext: IconI
  const CaretPrevious: IconI
  const CaretUp: IconI
  const Cart: IconI
  const Catalog: IconI
  const CatalogOption: IconI
  const Centos: IconI
  const Channel: IconI
  const ChapterAdd: IconI
  const ChapterNext: IconI
  const ChapterPrevious: IconI
  const Chat: IconI
  const ChatOption: IconI
  const Checkbox: IconI
  const CheckboxSelected: IconI
  const Checkmark: IconI
  const Chrome: IconI
  const CircleInformation: IconI
  const CirclePlay: IconI
  const CircleQuestion: IconI
  const Clear: IconI
  const ClearOption: IconI
  const Cli: IconI
  const Clipboard: IconI
  const Clock: IconI
  const Clone: IconI
  const Close: IconI
  const ClosedCaption: IconI
  const Cloud: IconI
  const CloudComputer: IconI
  const CloudDownload: IconI
  const CloudSoftware: IconI
  const CloudUpload: IconI
  const Cloudlinux: IconI
  const Cluster: IconI
  const CoatCheck: IconI
  const Code: IconI
  const CodeSandbox: IconI
  const Codepen: IconI
  const Columns: IconI
  const Command: IconI
  const Compare: IconI
  const Compass: IconI
  const Compliance: IconI
  const Configure: IconI
  const Connect: IconI
  const Connectivity: IconI
  const Contact: IconI
  const ContactInfo: IconI
  const Contract: IconI
  const Copy: IconI
  const CreativeCommons: IconI
  const CreditCard: IconI
  const Css3: IconI
  const Cube: IconI
  const Cubes: IconI
  const Currency: IconI
  const Cursor: IconI
  const Cut: IconI
  const Cycle: IconI
  const Dashboard: IconI
  const Database: IconI
  const Debian: IconI
  const Deliver: IconI
  const Deploy: IconI
  const Descend: IconI
  const Desktop: IconI
  const Detach: IconI
  const Device: IconI
  const Diamond: IconI
  const Directions: IconI
  const Disc: IconI
  const Dislike: IconI
  const Docker: IconI
  const Document: IconI
  const DocumentCloud: IconI
  const DocumentConfig: IconI
  const DocumentCsv: IconI
  const DocumentDownload: IconI
  const DocumentExcel: IconI
  const DocumentImage: IconI
  const DocumentLocked: IconI
  const DocumentMissing: IconI
  const DocumentNotes: IconI
  const DocumentOutlook: IconI
  const DocumentPdf: IconI
  const DocumentPerformance: IconI
  const DocumentPpt: IconI
  const DocumentRtf: IconI
  const DocumentSound: IconI
  const DocumentStore: IconI
  const DocumentTest: IconI
  const DocumentText: IconI
  const DocumentThreat: IconI
  const DocumentTime: IconI
  const DocumentTransfer: IconI
  const DocumentTxt: IconI
  const DocumentUpdate: IconI
  const DocumentUpload: IconI
  const DocumentUser: IconI
  const DocumentVerified: IconI
  const DocumentVideo: IconI
  const DocumentWindows: IconI
  const DocumentWord: IconI
  const DocumentZip: IconI
  const Domain: IconI
  const Dos: IconI
  const Down: IconI
  const Download: IconI
  const Drag: IconI
  const Drawer: IconI
  const DriveCage: IconI
  const Dropbox: IconI
  const Duplicate: IconI
  const Dxc: IconI
  const Edge: IconI
  const Edit: IconI
  const Eject: IconI
  const Elevator: IconI
  const Emergency: IconI
  const Emoji: IconI
  const EmptyCircle: IconI
  const Erase: IconI
  const Escalator: IconI
  const Expand: IconI
  const Facebook: IconI
  const FacebookOption: IconI
  const Fan: IconI
  const FastForward: IconI
  const Favorite: IconI
  const Fedora: IconI
  const Filter: IconI
  const FingerPrint: IconI
  const Fireball: IconI
  const Firefox: IconI
  const Flag: IconI
  const FlagFill: IconI
  const Folder: IconI
  const FolderCycle: IconI
  const FolderOpen: IconI
  const FormAdd: IconI
  const FormAttachment: IconI
  const FormCalendar: IconI
  const FormCheckmark: IconI
  const FormClock: IconI
  const FormClose: IconI
  const FormCut: IconI
  const FormDown: IconI
  const FormEdit: IconI
  const FormFilter: IconI
  const FormFolder: IconI
  const FormLocation: IconI
  const FormLock: IconI
  const FormNext: IconI
  const FormNextLink: IconI
  const FormPrevious: IconI
  const FormPreviousLink: IconI
  const FormRefresh: IconI
  const FormSchedule: IconI
  const FormSearch: IconI
  const FormSubtract: IconI
  const FormTrash: IconI
  const FormUp: IconI
  const FormUpload: IconI
  const FormView: IconI
  const FormViewHide: IconI
  const ForwardTen: IconI
  const Freebsd: IconI
  const Gallery: IconI
  const Gamepad: IconI
  const Gift: IconI
  const Github: IconI
  const Globe: IconI
  const Golang: IconI
  const Google: IconI
  const GooglePlus: IconI
  const GoogleWallet: IconI
  const Gremlin: IconI
  const Grid: IconI
  const Grommet: IconI
  const Group: IconI
  const Grow: IconI
  const Hadoop: IconI
  const Halt: IconI
  const Help: IconI
  const Heroku: IconI
  const History: IconI
  const Home: IconI
  const Horton: IconI
  const Host: IconI
  const HostMaintenance: IconI
  const Hp: IconI
  const Hpe: IconI
  const HpeLabs: IconI
  const Hpi: IconI
  const Html5: IconI
  const IceCream: IconI
  const Image: IconI
  const Impact: IconI
  const InProgress: IconI
  const Inbox: IconI
  const Indicator: IconI
  const Info: IconI
  const Inherit: IconI
  const Inspect: IconI
  const Instagram: IconI
  const Install: IconI
  const InstallOption: IconI
  const Integration: IconI
  const InternetExplorer: IconI
  const Italic: IconI
  const Iteration: IconI
  const Java: IconI
  const Keyboard: IconI
  const Language: IconI
  const Launch: IconI
  const Layer: IconI
  const License: IconI
  const Like: IconI
  const LineChart: IconI
  const Link: IconI
  const LinkBottom: IconI
  const LinkDown: IconI
  const LinkNext: IconI
  const LinkPrevious: IconI
  const LinkTop: IconI
  const LinkUp: IconI
  const Linkedin: IconI
  const LinkedinOption: IconI
  const Local: IconI
  const Location: IconI
  const LocationPin: IconI
  const Lock: IconI
  const Login: IconI
  const Logout: IconI
  const Lounge: IconI
  const Magic: IconI
  const Mail: IconI
  const MailOption: IconI
  const Mandriva: IconI
  const Manual: IconI
  const Map: IconI
  const MapLocation: IconI
  const Mastercard: IconI
  const Medium: IconI
  const Menu: IconI
  const Microfocus: IconI
  const Microphone: IconI
  const Money: IconI
  const Monitor: IconI
  const Monospace: IconI
  const More: IconI
  const Multimedia: IconI
  const Multiple: IconI
  const Music: IconI
  const Mysql: IconI
  const Navigate: IconI
  const Network: IconI
  const New: IconI
  const NewWindow: IconI
  const Next: IconI
  const Nodes: IconI
  const Norton: IconI
  const Note: IconI
  const Notes: IconI
  const Notification: IconI
  const ObjectGroup: IconI
  const ObjectUngroup: IconI
  const OfflineStorage: IconI
  const Onedrive: IconI
  const Opera: IconI
  const Optimize: IconI
  const Oracle: IconI
  const OrderedList: IconI
  const Organization: IconI
  const Overview: IconI
  const Paint: IconI
  const Pan: IconI
  const Pause: IconI
  const PauseFill: IconI
  const Paypal: IconI
  const Performance: IconI
  const PersonalComputer: IconI
  const PieChart: IconI
  const PiedPiper: IconI
  const Pin: IconI
  const Pinterest: IconI
  const Plan: IconI
  const Play: IconI
  const PlayFill: IconI
  const Power: IconI
  const PowerCycle: IconI
  const PowerForceShutdown: IconI
  const PowerReset: IconI
  const PowerShutdown: IconI
  const Previous: IconI
  const Print: IconI
  const ProductHunt: IconI
  const Projects: IconI
  const Radial: IconI
  const RadialSelected: IconI
  const Raspberry: IconI
  const Reactjs: IconI
  const Reddit: IconI
  const Redhat: IconI
  const Redo: IconI
  const Refresh: IconI
  const Resources: IconI
  const Restaurant: IconI
  const Restroom: IconI
  const RestroomMen: IconI
  const RestroomWomen: IconI
  const Resume: IconI
  const Return: IconI
  const Revert: IconI
  const Rewind: IconI
  const Risk: IconI
  const Robot: IconI
  const RotateLeft: IconI
  const RotateRight: IconI
  const Rss: IconI
  const Run: IconI
  const SafariOption: IconI
  const Satellite: IconI
  const Save: IconI
  const Scan: IconI
  const Schedule: IconI
  const ScheduleNew: IconI
  const SchedulePlay: IconI
  const Schedules: IconI
  const Sco: IconI
  const Scorecard: IconI
  const Search: IconI
  const SearchAdvanced: IconI
  const Secure: IconI
  const Select: IconI
  const Selection: IconI
  const Semantics: IconI
  const Send: IconI
  const Server: IconI
  const ServerCluster: IconI
  const Servers: IconI
  const ServicePlay: IconI
  const Services: IconI
  const SettingsOption: IconI
  const Share: IconI
  const ShareOption: IconI
  const Shield: IconI
  const ShieldSecurity: IconI
  const Shift: IconI
  const Shop: IconI
  const Sidebar: IconI
  const Sign: IconI
  const Skype: IconI
  const Slack: IconI
  const Snapchat: IconI
  const Solaris: IconI
  const Sort: IconI
  const Spa: IconI
  const Split: IconI
  const Splits: IconI
  const Square: IconI
  const StackOverflow: IconI
  const Stakeholder: IconI
  const Star: IconI
  const StarHalf: IconI
  const StatusCritical: IconI
  const StatusCriticalSmall: IconI
  const StatusDisabled: IconI
  const StatusDisabledSmall: IconI
  const StatusGood: IconI
  const StatusGoodSmall: IconI
  const StatusInfo: IconI
  const StatusInfoSmall: IconI
  const StatusPlaceholder: IconI
  const StatusPlaceholderSmall: IconI
  const StatusUnknown: IconI
  const StatusUnknownSmall: IconI
  const StatusWarning: IconI
  const StatusWarningSmall: IconI
  const Steps: IconI
  const StepsOption: IconI
  const Stop: IconI
  const StopFill: IconI
  const Storage: IconI
  const StreetView: IconI
  const StrikeThrough: IconI
  const Stripe: IconI
  const Subscript: IconI
  const Subtract: IconI
  const SubtractCircle: IconI
  const Superscript: IconI
  const Support: IconI
  const Suse: IconI
  const Swift: IconI
  const Swim: IconI
  const Sync: IconI
  const System: IconI
  const Table: IconI
  const TableAdd: IconI
  const Tag: IconI
  const Tape: IconI
  const TapeOption: IconI
  const Target: IconI
  const Task: IconI
  const Tasks: IconI
  const Technology: IconI
  const Template: IconI
  const Terminal: IconI
  const Test: IconI
  const TestDesktop: IconI
  const TextAlignCenter: IconI
  const TextAlignFull: IconI
  const TextAlignLeft: IconI
  const TextAlignRight: IconI
  const TextWrap: IconI
  const Threats: IconI
  const ThreeD: IconI
  const ThreeDffects: IconI
  const Ticket: IconI
  const Tip: IconI
  const Toast: IconI
  const Tools: IconI
  const Tooltip: IconI
  const TopCorner: IconI
  const Train: IconI
  const Transaction: IconI
  const Trash: IconI
  const Tree: IconI
  const TreeOption: IconI
  const Trigger: IconI
  const Trophy: IconI
  const Troubleshoot: IconI
  const Tty: IconI
  const Tumblr: IconI
  const Turbolinux: IconI
  const Twitter: IconI
  const Ubuntu: IconI
  const Underline: IconI
  const Undo: IconI
  const Unlink: IconI
  const Unlock: IconI
  const UnorderedList: IconI
  const Up: IconI
  const Update: IconI
  const Upgrade: IconI
  const Upload: IconI
  const User: IconI
  const UserAdd: IconI
  const UserAdmin: IconI
  const UserExpert: IconI
  const UserFemale: IconI
  const UserManager: IconI
  const UserNew: IconI
  const UserPolice: IconI
  const UserSettings: IconI
  const UserWorker: IconI
  const Validate: IconI
  const Vend: IconI
  const Video: IconI
  const View: IconI
  const Vimeo: IconI
  const VirtualMachine: IconI
  const VirtualStorage: IconI
  const Visa: IconI
  const VmMaintenance: IconI
  const Vmware: IconI
  const Volume: IconI
  const VolumeControl: IconI
  const VolumeLow: IconI
  const VolumeMute: IconI
  const Vulnerability: IconI
  const Waypoint: IconI
  const Wheelchair: IconI
  const WheelchairActive: IconI
  const Wifi: IconI
  const WifiLow: IconI
  const WifiMedium: IconI
  const WifiNone: IconI
  const Windows: IconI
  const WindowsLegacy: IconI
  const Wordpress: IconI
  const Workshop: IconI
  const Yoga: IconI
  const Youtube: IconI
  const ZoomIn: IconI
  const ZoomOut: IconI

  // TODO: type icon utils
  const base: any
  const defaultProps: any
  const extendDefaultTheme: any
}
