// TypeScript Version: 3.0

declare module 'grommet-icons' {
  import React from 'react'

  type IconTheme = typeof import('./themes').base

  type ColorProp<Theme> = Theme extends IconTheme
    ? keyof Theme['global']['colors']
    : string

  type IconSizeProp<Theme> = Theme extends IconTheme
    ? keyof Theme['icon']['size']
    : string

  interface IconProps<Theme = object> {
    a11yTitle?: string
    size?: IconSizeProp<Theme>
    color?: ColorProp<Theme>
  }

  type Icon<Theme = object> = React.ComponentType<
    IconProps<Theme> & JSX.IntrinsicElements['svg']
  >

  const Accessibility: Icon
  const Achievement: Icon
  const Action: Icon
  const Actions: Icon
  const Ad: Icon
  const Add: Icon
  const AddCircle: Icon
  const Aed: Icon
  const Aggregate: Icon
  const Aid: Icon
  const AidOption: Icon
  const Alarm: Icon
  const Alert: Icon
  const Amazon: Icon
  const Amex: Icon
  const Analytics: Icon
  const Anchor: Icon
  const Android: Icon
  const Announce: Icon
  const Apple: Icon
  const Apps: Icon
  const Archive: Icon
  const Archlinux: Icon
  const Article: Icon
  const Aruba: Icon
  const Ascend: Icon
  const AssistListening: Icon
  const Atm: Icon
  const Attachment: Icon
  const Attraction: Icon
  const Baby: Icon
  const BackTen: Icon
  const Bar: Icon
  const BarChart: Icon
  const Basket: Icon
  const Bike: Icon
  const Bitcoin: Icon
  const Blank: Icon
  const BlockQuote: Icon
  const Blog: Icon
  const Bluetooth: Icon
  const Bold: Icon
  const Book: Icon
  const Bookmark: Icon
  const BottomCorner: Icon
  const Braille: Icon
  const Briefcase: Icon
  const Brush: Icon
  const Bug: Icon
  const Bundle: Icon
  const Bus: Icon
  const BusinessService: Icon
  const Cafeteria: Icon
  const Calculator: Icon
  const Calendar: Icon
  const Camera: Icon
  const Capacity: Icon
  const Car: Icon
  const CaretDown: Icon
  const CaretNext: Icon
  const CaretPrevious: Icon
  const CaretUp: Icon
  const Cart: Icon
  const Catalog: Icon
  const CatalogOption: Icon
  const Centos: Icon
  const Channel: Icon
  const ChapterAdd: Icon
  const ChapterNext: Icon
  const ChapterPrevious: Icon
  const Chat: Icon
  const ChatOption: Icon
  const Checkbox: Icon
  const CheckboxSelected: Icon
  const Checkmark: Icon
  const Chrome: Icon
  const CircleInformation: Icon
  const CirclePlay: Icon
  const CircleQuestion: Icon
  const Clear: Icon
  const ClearOption: Icon
  const Cli: Icon
  const Clipboard: Icon
  const Clock: Icon
  const Clone: Icon
  const Close: Icon
  const ClosedCaption: Icon
  const Cloud: Icon
  const CloudComputer: Icon
  const CloudDownload: Icon
  const CloudSoftware: Icon
  const CloudUpload: Icon
  const Cloudlinux: Icon
  const Cluster: Icon
  const CoatCheck: Icon
  const Code: Icon
  const CodeSandbox: Icon
  const Codepen: Icon
  const Columns: Icon
  const Command: Icon
  const Compare: Icon
  const Compass: Icon
  const Compliance: Icon
  const Configure: Icon
  const Connect: Icon
  const Connectivity: Icon
  const Contact: Icon
  const ContactInfo: Icon
  const Contract: Icon
  const Copy: Icon
  const CreativeCommons: Icon
  const CreditCard: Icon
  const Css3: Icon
  const Cube: Icon
  const Cubes: Icon
  const Currency: Icon
  const Cursor: Icon
  const Cut: Icon
  const Cycle: Icon
  const Dashboard: Icon
  const Database: Icon
  const Debian: Icon
  const Deliver: Icon
  const Deploy: Icon
  const Descend: Icon
  const Desktop: Icon
  const Detach: Icon
  const Device: Icon
  const Diamond: Icon
  const Directions: Icon
  const Disc: Icon
  const Dislike: Icon
  const Docker: Icon
  const Document: Icon
  const DocumentCloud: Icon
  const DocumentConfig: Icon
  const DocumentCsv: Icon
  const DocumentDownload: Icon
  const DocumentExcel: Icon
  const DocumentImage: Icon
  const DocumentLocked: Icon
  const DocumentMissing: Icon
  const DocumentNotes: Icon
  const DocumentOutlook: Icon
  const DocumentPdf: Icon
  const DocumentPerformance: Icon
  const DocumentPpt: Icon
  const DocumentRtf: Icon
  const DocumentSound: Icon
  const DocumentStore: Icon
  const DocumentTest: Icon
  const DocumentText: Icon
  const DocumentThreat: Icon
  const DocumentTime: Icon
  const DocumentTransfer: Icon
  const DocumentTxt: Icon
  const DocumentUpdate: Icon
  const DocumentUpload: Icon
  const DocumentUser: Icon
  const DocumentVerified: Icon
  const DocumentVideo: Icon
  const DocumentWindows: Icon
  const DocumentWord: Icon
  const DocumentZip: Icon
  const Domain: Icon
  const Dos: Icon
  const Down: Icon
  const Download: Icon
  const Drag: Icon
  const Drawer: Icon
  const DriveCage: Icon
  const Dropbox: Icon
  const Duplicate: Icon
  const Dxc: Icon
  const Edge: Icon
  const Edit: Icon
  const Eject: Icon
  const Elevator: Icon
  const Emergency: Icon
  const Emoji: Icon
  const EmptyCircle: Icon
  const Erase: Icon
  const Escalator: Icon
  const Expand: Icon
  const Facebook: Icon
  const FacebookOption: Icon
  const Fan: Icon
  const FastForward: Icon
  const Favorite: Icon
  const Fedora: Icon
  const Filter: Icon
  const FingerPrint: Icon
  const Fireball: Icon
  const Firefox: Icon
  const Flag: Icon
  const FlagFill: Icon
  const Folder: Icon
  const FolderCycle: Icon
  const FolderOpen: Icon
  const FormAdd: Icon
  const FormAttachment: Icon
  const FormCalendar: Icon
  const FormCheckmark: Icon
  const FormClock: Icon
  const FormClose: Icon
  const FormCut: Icon
  const FormDown: Icon
  const FormEdit: Icon
  const FormFilter: Icon
  const FormFolder: Icon
  const FormLocation: Icon
  const FormLock: Icon
  const FormNext: Icon
  const FormNextLink: Icon
  const FormPrevious: Icon
  const FormPreviousLink: Icon
  const FormRefresh: Icon
  const FormSchedule: Icon
  const FormSearch: Icon
  const FormSubtract: Icon
  const FormTrash: Icon
  const FormUp: Icon
  const FormUpload: Icon
  const FormView: Icon
  const FormViewHide: Icon
  const ForwardTen: Icon
  const Freebsd: Icon
  const Gallery: Icon
  const Gamepad: Icon
  const Gift: Icon
  const Github: Icon
  const Globe: Icon
  const Golang: Icon
  const Google: Icon
  const GooglePlus: Icon
  const GoogleWallet: Icon
  const Gremlin: Icon
  const Grid: Icon
  const Grommet: Icon
  const Group: Icon
  const Grow: Icon
  const Hadoop: Icon
  const Halt: Icon
  const Help: Icon
  const Heroku: Icon
  const History: Icon
  const Home: Icon
  const Horton: Icon
  const Host: Icon
  const HostMaintenance: Icon
  const Hp: Icon
  const Hpe: Icon
  const HpeLabs: Icon
  const Hpi: Icon
  const Html5: Icon
  const IceCream: Icon
  const Image: Icon
  const Impact: Icon
  const InProgress: Icon
  const Inbox: Icon
  const Indicator: Icon
  const Info: Icon
  const Inherit: Icon
  const Inspect: Icon
  const Instagram: Icon
  const Install: Icon
  const InstallOption: Icon
  const Integration: Icon
  const InternetExplorer: Icon
  const Italic: Icon
  const Iteration: Icon
  const Java: Icon
  const Keyboard: Icon
  const Language: Icon
  const Launch: Icon
  const Layer: Icon
  const License: Icon
  const Like: Icon
  const LineChart: Icon
  const Link: Icon
  const LinkBottom: Icon
  const LinkDown: Icon
  const LinkNext: Icon
  const LinkPrevious: Icon
  const LinkTop: Icon
  const LinkUp: Icon
  const Linkedin: Icon
  const LinkedinOption: Icon
  const Local: Icon
  const Location: Icon
  const LocationPin: Icon
  const Lock: Icon
  const Login: Icon
  const Logout: Icon
  const Lounge: Icon
  const Magic: Icon
  const Mail: Icon
  const MailOption: Icon
  const Mandriva: Icon
  const Manual: Icon
  const Map: Icon
  const MapLocation: Icon
  const Mastercard: Icon
  const Medium: Icon
  const Menu: Icon
  const Microfocus: Icon
  const Microphone: Icon
  const Money: Icon
  const Monitor: Icon
  const Monospace: Icon
  const More: Icon
  const Multimedia: Icon
  const Multiple: Icon
  const Music: Icon
  const Mysql: Icon
  const Navigate: Icon
  const Network: Icon
  const New: Icon
  const NewWindow: Icon
  const Next: Icon
  const Nodes: Icon
  const Norton: Icon
  const Note: Icon
  const Notes: Icon
  const Notification: Icon
  const ObjectGroup: Icon
  const ObjectUngroup: Icon
  const OfflineStorage: Icon
  const Onedrive: Icon
  const Opera: Icon
  const Optimize: Icon
  const Oracle: Icon
  const OrderedList: Icon
  const Organization: Icon
  const Overview: Icon
  const Paint: Icon
  const Pan: Icon
  const Pause: Icon
  const PauseFill: Icon
  const Paypal: Icon
  const Performance: Icon
  const PersonalComputer: Icon
  const PieChart: Icon
  const PiedPiper: Icon
  const Pin: Icon
  const Pinterest: Icon
  const Plan: Icon
  const Play: Icon
  const PlayFill: Icon
  const Power: Icon
  const PowerCycle: Icon
  const PowerForceShutdown: Icon
  const PowerReset: Icon
  const PowerShutdown: Icon
  const Previous: Icon
  const Print: Icon
  const ProductHunt: Icon
  const Projects: Icon
  const Radial: Icon
  const RadialSelected: Icon
  const Raspberry: Icon
  const Reactjs: Icon
  const Reddit: Icon
  const Redhat: Icon
  const Redo: Icon
  const Refresh: Icon
  const Resources: Icon
  const Restaurant: Icon
  const Restroom: Icon
  const RestroomMen: Icon
  const RestroomWomen: Icon
  const Resume: Icon
  const Return: Icon
  const Revert: Icon
  const Rewind: Icon
  const Risk: Icon
  const Robot: Icon
  const RotateLeft: Icon
  const RotateRight: Icon
  const Rss: Icon
  const Run: Icon
  const SafariOption: Icon
  const Satellite: Icon
  const Save: Icon
  const Scan: Icon
  const Schedule: Icon
  const ScheduleNew: Icon
  const SchedulePlay: Icon
  const Schedules: Icon
  const Sco: Icon
  const Scorecard: Icon
  const Search: Icon
  const SearchAdvanced: Icon
  const Secure: Icon
  const Select: Icon
  const Selection: Icon
  const Semantics: Icon
  const Send: Icon
  const Server: Icon
  const ServerCluster: Icon
  const Servers: Icon
  const ServicePlay: Icon
  const Services: Icon
  const SettingsOption: Icon
  const Share: Icon
  const ShareOption: Icon
  const Shield: Icon
  const ShieldSecurity: Icon
  const Shift: Icon
  const Shop: Icon
  const Sidebar: Icon
  const Sign: Icon
  const Skype: Icon
  const Slack: Icon
  const Snapchat: Icon
  const Solaris: Icon
  const Sort: Icon
  const Spa: Icon
  const Split: Icon
  const Splits: Icon
  const Square: Icon
  const StackOverflow: Icon
  const Stakeholder: Icon
  const Star: Icon
  const StarHalf: Icon
  const StatusCritical: Icon
  const StatusCriticalSmall: Icon
  const StatusDisabled: Icon
  const StatusDisabledSmall: Icon
  const StatusGood: Icon
  const StatusGoodSmall: Icon
  const StatusInfo: Icon
  const StatusInfoSmall: Icon
  const StatusPlaceholder: Icon
  const StatusPlaceholderSmall: Icon
  const StatusUnknown: Icon
  const StatusUnknownSmall: Icon
  const StatusWarning: Icon
  const StatusWarningSmall: Icon
  const Steps: Icon
  const StepsOption: Icon
  const Stop: Icon
  const StopFill: Icon
  const Storage: Icon
  const StreetView: Icon
  const StrikeThrough: Icon
  const Stripe: Icon
  const Subscript: Icon
  const Subtract: Icon
  const SubtractCircle: Icon
  const Superscript: Icon
  const Support: Icon
  const Suse: Icon
  const Swift: Icon
  const Swim: Icon
  const Sync: Icon
  const System: Icon
  const Table: Icon
  const TableAdd: Icon
  const Tag: Icon
  const Tape: Icon
  const TapeOption: Icon
  const Target: Icon
  const Task: Icon
  const Tasks: Icon
  const Technology: Icon
  const Template: Icon
  const Terminal: Icon
  const Test: Icon
  const TestDesktop: Icon
  const TextAlignCenter: Icon
  const TextAlignFull: Icon
  const TextAlignLeft: Icon
  const TextAlignRight: Icon
  const TextWrap: Icon
  const Threats: Icon
  const ThreeD: Icon
  const ThreeDffects: Icon
  const Ticket: Icon
  const Tip: Icon
  const Toast: Icon
  const Tools: Icon
  const Tooltip: Icon
  const TopCorner: Icon
  const Train: Icon
  const Transaction: Icon
  const Trash: Icon
  const Tree: Icon
  const TreeOption: Icon
  const Trigger: Icon
  const Trophy: Icon
  const Troubleshoot: Icon
  const Tty: Icon
  const Tumblr: Icon
  const Turbolinux: Icon
  const Twitter: Icon
  const Ubuntu: Icon
  const Underline: Icon
  const Undo: Icon
  const Unlink: Icon
  const Unlock: Icon
  const UnorderedList: Icon
  const Up: Icon
  const Update: Icon
  const Upgrade: Icon
  const Upload: Icon
  const User: Icon
  const UserAdd: Icon
  const UserAdmin: Icon
  const UserExpert: Icon
  const UserFemale: Icon
  const UserManager: Icon
  const UserNew: Icon
  const UserPolice: Icon
  const UserSettings: Icon
  const UserWorker: Icon
  const Validate: Icon
  const Vend: Icon
  const Video: Icon
  const View: Icon
  const Vimeo: Icon
  const VirtualMachine: Icon
  const VirtualStorage: Icon
  const Visa: Icon
  const VmMaintenance: Icon
  const Vmware: Icon
  const Volume: Icon
  const VolumeControl: Icon
  const VolumeLow: Icon
  const VolumeMute: Icon
  const Vulnerability: Icon
  const Waypoint: Icon
  const Wheelchair: Icon
  const WheelchairActive: Icon
  const Wifi: Icon
  const WifiLow: Icon
  const WifiMedium: Icon
  const WifiNone: Icon
  const Windows: Icon
  const WindowsLegacy: Icon
  const Wordpress: Icon
  const Workshop: Icon
  const Yoga: Icon
  const Youtube: Icon
  const ZoomIn: Icon
  const ZoomOut: Icon
  const base: Icon
  const defaultProps: Icon
  const extendDefaultTheme: Icon
}
